modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/CAS-ual-TY/Extra-Trades/issues"

[[mods]]
    modId="extratrades"
    version="${file.jarVersion}"
    displayName="Extra Trades"
    displayURL="https://github.com/CAS-ual-TY/Extra-Trades"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team"
    authors="CAS_ual_TY"
    description="This is a mini-mod adding some trades to the existing villagers. Basically, most of the things that were only either buyable or sellable, can now both be bought and sold. And additionally you can now buy some useful items which you could not buy before."
